[package]
name = "TradeLeague"
version = "1.0.0"
authors = ["TradeLeague Team"]

[addresses]
tradeleague = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]